# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170410_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Meal')),
            ],
            bases=('catalog.meal',),
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Meal')),
            ],
            bases=('catalog.meal',),
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Meal')),
            ],
            bases=('catalog.meal',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Meal')),
            ],
            bases=('catalog.meal',),
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Meal')),
            ],
            bases=('catalog.meal',),
        ),
    ]
