# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_desserts_drinks_hot_pizza_salads'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
